Vagrant.configure(2) do |config|
  config.vm.box = "max/centos66-163"
  config.vm.hostname = "sphinx-test.max.com"
  config.vm.provision 'Checking gem environment', type: :host_shell do |host_shell|
        host_shell.abort_on_nonzero = true
        host_shell.inline = "gem environment"
  end
end
